using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using HappyPhoton.Models;
using HappyPhoton.Services;
using Xunit;

namespace HappyPhoton.Tests;

// G1 hashes were generated by this workload against git archive 8c489f50b7e61e16b10c61c45458684deae2c8a1.
// Only the archived test copy wrote the sorted hashes before comparison; production sources were unchanged.
// Hash UTF-8 canonical document JSON and exact saved preset bytes, with fixed personal IDs.
public sealed class FinishingCanonicalBytesTests(ITestOutputHelper output)
{
    [Fact]
    public async Task SaveAndReloadMatchPreBuiltInCanonicalBytes()
    {
        using var directory = new TemporaryDirectory();
        using var catalog = new CatalogService(Path.Combine(directory.Path, "catalog"));
        await catalog.InitializeAsync();
        var hashes = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var fixtures = SyncTransferParityCorpus.Sources().Concat(SyncTransferParityCorpus.Destinations());
        var index = 0;

        foreach (var fixture in fixtures)
        {
            var presetDirectory = Path.Combine(directory.Path, $"presets-{index}");
            Directory.CreateDirectory(presetDirectory);
            const string presetId = "user_finishing_canonical";
            var presetPath = Path.Combine(presetDirectory, presetId + ".json");
            await File.WriteAllTextAsync(presetPath, JsonSerializer.Serialize(new UserPresetFile
            {
                Id = presetId, Name = "Canonical", Settings = new EditSettings()
            }));
            var presets = new PresetService(presetDirectory);
            await presets.InitializeAsync();
            await presets.SaveUserPresetAsync("Canonical", fixture.Settings, presetId);
            var presetBytes = await File.ReadAllBytesAsync(presetPath);
            // The frozen preset hashes use Windows JSON formatting; retain exact reload checks below.
            hashes.Add($"{fixture.Name}/preset", Hash(Encoding.UTF8.GetBytes(
                Encoding.UTF8.GetString(presetBytes).ReplaceLineEndings("\r\n"))));
            var reopened = new PresetService(presetDirectory);
            await reopened.InitializeAsync();
            var preset = Assert.Single(reopened.UserPresets);
            await reopened.SaveUserPresetAsync(preset.Name, preset.Settings, preset.Id);
            Assert.Equal(presetBytes, await File.ReadAllBytesAsync(presetPath));

            foreach (var marker in new string?[] { null, presetId })
            {
                var settings = fixture.Settings.Clone();
                settings.AppliedPresetId = marker;
                var key = $"{fixture.Name}/document/{(marker == null ? "unmarked" : "personal")}";
                var canonical = EditSettingsJson.Serialize(settings);
                hashes.Add(key, Hash(Encoding.UTF8.GetBytes(canonical)));
                var path = Path.Combine(directory.Path, $"photo-{index++}.jpg");
                var id = await catalog.GetOrCreateImageAsync(path);
                await catalog.SaveEditSettingsAsync(id, settings);
                var reloaded = (await catalog.LoadImageStatesAsync([path]))[path].Single().EditSettings;
                Assert.Equal(canonical, EditSettingsJson.Serialize(reloaded));
                await catalog.SaveEditSettingsAsync(id, reloaded);
                var twice = (await catalog.LoadImageStatesAsync([path]))[path].Single().EditSettings;
                Assert.Equal(canonical, EditSettingsJson.Serialize(twice));
            }
        }

        var baseline = Path.Combine(GoldenTestPaths.AssetDirectory, "finishing-looks", "canonical-sha256.json");
        var expected = JsonSerializer.Deserialize<SortedDictionary<string, string>>(File.ReadAllText(baseline))!;
        Assert.Equal(expected.Keys.Order(StringComparer.Ordinal), hashes.Keys);
        var differences = hashes.Keys.Where(key => expected[key] != hashes[key]).ToArray();
        output.WriteLine($"G1: {hashes.Count} canonical hashes; {differences.Length} differences.");
        Assert.True(differences.Length == 0, string.Join(", ", differences));
    }

    private static string Hash(byte[] bytes) => Convert.ToHexString(SHA256.HashData(bytes));
}
